language: C

notifications:
  email: false

sudo: required

env:
    matrix:
        - HOST_CLOUD=gce_clean_images.sh
        - HOST_CLOUD=aws_clean_images.sh
        - HOST_CLOUD=os_clean_images.sh
        - HOST_CLOUD=az_clean_images.sh

before_install:
    # Due to the following Bug: https://github.com/travis-ci/travis-ci/issues/7940
    # To be removed in future revisions once bug is solved
    - sudo rm -f /etc/boto.cfg

install: true

before_script:
    # Installing common tools (pip and jq) and check bash scripts
    - sudo apt-get update
    - sudo apt-get install shellcheck jq python-pip -y
    - pip -V
    - pip install --upgrade pip
    - shellcheck $(find . -type f -name "*.sh")
  
script:
    - ./$HOST_CLOUD
    