---
language: C

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck # code review tool
      - jq
      - python-pip

env:
  global:
    - ANSIBLE_LINT_VERSION=3.4.15
    - YAMLLINT_VERSION=1.8.1
  matrix:
    - CRON_SCRIPT=gce_clean_images.sh
    - CRON_SCRIPT=aws_clean_images.sh
    - CRON_SCRIPT=os_clean_images.sh
    - CRON_SCRIPT=az_clean_images.sh

before_install:
  # Due to the following Bug: https://github.com/travis-ci/travis-ci/issues/7940
  # To be removed in future revisions once bug is solved
  - sudo rm -f /etc/boto.cfg

install:
  # Install code review tools
  - sudo pip install --upgrade pip
  - >
    sudo pip install
    ansible-lint=="${ANSIBLE_LINT_VERSION}"
    yamllint=="${YAMLLINT_VERSION}"

before_script:
  # Check
  # check Shell
  - shellcheck *.sh
  - docker run -v "$(pwd)":/sh -w /sh jamesmstone/shfmt -i 2 -w *.sh
  - git diff --exit-code
  # check YAML
  - yamllint -c .yamllint.yml -s .travis.yml

script:
  - ./$CRON_SCRIPT

notifications:
  email: false
  slack:
    secure: >
      plMWyTiljmwpUuA6mb8Q914+M25wxmuz+j3fgb2ZOmRsUG9xNS+h6yNVPbulbay0XTlElCvQs/
      BgmRjauwRQ6FNOopjrazFW30Gx6hf/ZEZw3VN4KT2nQnwZD251D5iRNYrYVuJgKgJMhVkGJuxU
      3DlMC3LRQ4eI/gHKpEpmAZ9vSJ/zeyXQvTjtmII8BqDAsw/rXWVFXqogcospxET//snhvGtBu8
      7TUECgeRkiXigjmEDhnbbf/xxU6jlbfLGMy+fdWwdklN/Y03iw1DP76/LX/G+fJhFsEcYQN1Xh
      du9VD9xG1w0krWwe8EtDeMXdkYYOzXvFLfLZ/LXKICmK8jti2HuPwuAlo6P+XyBtb7WWWFBVBc
      FyeYWM0C0VDKaJg/o2XwR67CJN65d1qaPEEhqx51PGVsnOFmrDZkTiZe8QTnZ0NnTMfWqFHSEK
      +6Z7+xqrWwK4gj5TrJZiAxXAw0EurbYnkI5ccrxKf9dJdQJuhoW7DVxXxSagfSd4IOn/TXSPOD
      CKHqqCcctFvGhDRSlJVT+/okstkSROLhaGPdv4aLLBi7L+s04AJSzrkJebKfgfF/h8w6d9JfCy
      APpBRlUiRb6l7vk8lDExR4odLZFmJsswtbpjjVFhhyZOnuZn+8GlmgotYfIABkvJayFGtPgJeB
      EQLcqCSugMbUUzL4E=
